### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by 2856571872** [DamonHu/HDHUD#1]
显示自定义的时候Snapkit会导致View不显示，使用frame即可
`static func showView(view: UIView, superView: UIView?) {
        //show new view
        var tmpSuperView = superView
        if tmpSuperView == nil {
            tmpSuperView = HDCommonToolsSwift.shared.getCurrentNormalWindow()
        }
        guard let tSuperView = tmpSuperView else { return }

        tSuperView.addSubview(mContentBGView)
        mContentBGView.frame = tSuperView.bounds

        mContentBGView.insertSubview(view, at: 0)
        view.center.x = mContentBGView.center.x + contentOffset.x
        view.center.y = mContentBGView.center.y + contentOffset.y
  
    }`

**Comment by DamonHu** [comment]
可能readme文档里面没写清除，添加的自定义视图是位置，view自己要写大小的，比如在view添加之前，设置

```
make.width.equal(40)
make.height.equal(60)
```
这样

**Comment by 2856571872** [comment]
`
        let size = view.frame.size
        view.snp.makeConstraints { (make) in
            make.centerX.equalToSuperview().offset(contentOffset.x)
            make.centerY.equalToSuperview().offset(contentOffset.y)
            
            if size.width != 0{
                make.width.equalTo(size.width)
            }
            
            if size.height != 0 {
                make.height.equalTo(size.height)
            }
        }
//
        tSuperView.layoutIfNeeded()
        print("aaa----\(view.frame)")
`

**Comment by DamonHu** [comment]
view如果在外层设置了frame，里面的width和height不用再重复设置的。像你上面帖的这个代码，如果view.frame.size已经设置过了，后面的width和height.equalTo不设置也可以的。相当于已经有了

**Comment by DamonHu** [comment]
pod已更新1.2.3版本，修复了上面说的frame和autoLayout混用的问题，纠正一下上面说的，如果`translatesAutoresizingMaskIntoConstraints`是`false`，frame是不会自动添加到autoLayout的约束里面的。`snapKit`已经默认设置为`false`了。
